GET http://localhost/ebook/hello
Accept: application/json

###

POST http://localhost/test/hello/post
Content-Type: application/x-www-form-urlencoded

name=TEST

###

GET http://localhost/ebook/list?name=My
Accept: application/json
