GET http://localhost/test/hello
Accept: application/json

###

POST http://localhost/test/hello/post
Content-Type: application/x-www-form-urlencoded

name=TEST

###

POST http://localhost/test/hello/post
Content-Type: application/x-www-form-urlencoded

name=TEST2